### ISSUE TITLE
Alpha bug reports

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/Saika#2]
- [x] 附魔源定义后只能使用完全匹配的物品。
- [x] 附魔界面更新偶发 bug，只有放入附魔书是才会更新结果，但是结果不更新时点击依旧是可以附魔的（此问题在所有 UI 里都会出现
- [x] 所有物品（甚至附魔书）都可以附魔（参考 nu enchant 只有工具和武器类才能被附魔
- [x] 堆叠物品会被一起附魔
- [x] 附魔有经验值判定，但是没有扣除
- [x] 消魔源可以被扣除多个
- [x] 消魔没有返还经验
- [x] 物品只有黑名单内的附魔时报错 https://github.com/NyaaCat/Saika/issues/2#issuecomment-497938675
- [x] 删除 `enchant.yml`，`saika reload` 后再新定义一个附魔源会把内存里的所有附魔源都写回配置文件
- [x] 相同最低消耗，不同权重（2 和 100）的铸造物品的出率基本相同，更低档的物品出率正常。该问题只出现在这些物品都是最高消耗值的情况下。https://github.com/NyaaCat/Saika/blob/8840414631c0a64b7f7677f740bfd905eff1ea03/src/main/java/cat/nyaa/saika/forge/roll/Roller.java#L34 `Math.round(((double) maxCostItem.getWeight()) *` 改为 `Math.round(((double) forgeableItem.getWeight()) *`

WIP

**Comment by phoenixlzx** [comment]
```
[19:56:28 ERROR]: Could not pass event InventoryClickEvent to Saika vv1.0
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_171]
        at cat.nyaa.saika.forge.ui.RepulseUi.onRepulse(RepulseUi.java:109) ~[?:?]
        at cat.nyaa.saika.forge.ui.ForgeUiEvents.repulseClicked(ForgeUiEvents.java:133) ~[?:?]
        at cat.nyaa.saika.forge.ui.ForgeUiEvents.onInventoryClick(ForgeUiEvents.java:112) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor236.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-626]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-626]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-626]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2288) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-626]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-626]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[19:56:28 FATAL]: Error executing task
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.inventory.CraftInventoryCustom$MinecraftInventory cannot be cast to net.minecraft.server.v1_13_R2.TileEntityFurnace
        at net.minecraft.server.v1_13_R2.SlotFurnaceResult.c(SlotFurnaceResult.java:46) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.SlotFurnaceResult.a(SlotFurnaceResult.java:33) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.Container.a(Container.java:286) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2296) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-626]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-626]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-626]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by ReinWD** [comment]
> * [x]  附魔界面更新偶发 bug，只有放入附魔书是才会更新结果，但是结果不更新时点击依旧是可以附魔的（此问题在所有 UI 里都会出现

WIP

> * [x]  附魔有经验值判定，但是没有扣除

复现方式请求
https://github.com/NyaaCat/Saika/blob/8840414631c0a64b7f7677f740bfd905eff1ea03/src/main/java/cat/nyaa/saika/forge/ui/ForgeUiEvents.java#L230
此处已扣除玩家经验

**Comment by ReinWD** [comment]
all fixed
